version: "3.9"
services:
  back:
    build: .
    ports:
      - "3333:3333"
    networks:
      - mynetwork
    environment:
      - NODE_ENV=development
      - PORT=3333
networks: 
  mynetwork:
    external: true
